In [2]:
pip install pandas

Requirement already satisfied: pandas in .\project\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in .\project\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in .\project\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\project\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\project\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
print(pd.__version__)

3.0.3

In [4]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'col',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_hdf',
 'read_html',
 'read_iceberg',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'wide_to_long']

In [5]:
x=["lakshmi","vasu","kalyani","vignesh","keerthana"]
data=pd.Series(x,index=[101,102,103,104,105])
print(data)

101      lakshmi
102         vasu
103      kalyani
104      vignesh
105    keerthana
dtype: str

In [10]:
data=[[101,"Lakshmi",90],[102,"Vasu",89],[103,"Kalyani",94],[104,"Vignesh",87]]
df=pd.Series(data)
print(df)
table=pd.DataFrame(data,columns=["ID","NAME","MARKS"])
print(table)

0    [101, Lakshmi, 90]
1       [102, Vasu, 89]
2    [103, Kalyani, 94]
3    [104, Vignesh, 87]
dtype: object
    ID     NAME  MARKS
0  101  Lakshmi     90
1  102     Vasu     89
2  103  Kalyani     94
3  104  Vignesh     87

In [19]:
data={ "id":[101,102,103,104],"name":["Lakshmi", "vasu","kalyani","vignesh"]}
print(pd.DataFrame(data))
data["marks"]=[100,199,200,230]
data["dept"]=["MCA","MSC","CSE","MEC"]
print(pd.DataFrame(data))

    id     name
0  101  Lakshmi
1  102     vasu
2  103  kalyani
3  104  vignesh
    id     name  marks dept
0  101  Lakshmi    100  MCA
1  102     vasu    199  MSC
2  103  kalyani    200  CSE
3  104  vignesh    230  MEC

In [21]:
df=pd.read_csv("summer.csv")
print(df)

       Year    City      Sport           Discipline  \
0      1896  Athens   Aquatics             Swimming
1      1896  Athens   Aquatics             Swimming
2      1896  Athens   Aquatics             Swimming
3      1896  Athens   Aquatics             Swimming
4      1896  Athens   Aquatics             Swimming
...     ...     ...        ...                  ...
31160  2012  London  Wrestling  Wrestling Freestyle
31161  2012  London  Wrestling  Wrestling Freestyle
31162  2012  London  Wrestling  Wrestling Freestyle
31163  2012  London  Wrestling  Wrestling Freestyle
31164  2012  London  Wrestling  Wrestling Freestyle

                         Athlete Country Gender                       Event  \
0                  HAJOS, Alfred     HUN    Men              100M Freestyle
1               HERSCHMANN, Otto     AUT    Men              100M Freestyle
2              DRIVAS, Dimitrios     GRE    Men  100M Freestyle For Sailors
3             MALOKINIS, Ioannis     GRE    Men  100M Freestyle For Sailors
4             CHASAPIS, Spiridon     GRE    Men  100M Freestyle For Sailors
...                          ...     ...    ...                         ...
31160         JANIKOWSKI, Damian     POL    Men                    Wg 84 KG
31161  REZAEI, Ghasem Gholamreza     IRI    Men                    Wg 96 KG
31162             TOTROV, Rustam     RUS    Men                    Wg 96 KG
31163          ALEKSANYAN, Artur     ARM    Men                    Wg 96 KG
31164             LIDBERG, Jimmy     SWE    Men                    Wg 96 KG

        Medal
0        Gold
1      Silver
2      Bronze
3        Gold
4      Silver
...       ...
31160  Bronze
31161    Gold
31162  Silver
31163  Bronze
31164  Bronze

[31165 rows x 9 columns]

In [23]:
df[df["Sport"]=="Wrestling"]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
148,1896,Athens,Wrestling,Wrestling Gre-R,"CHRISTOPOULOS, Stephanos",GRE,Men,Open Event,Bronze
149,1896,Athens,Wrestling,Wrestling Gre-R,"SCHUMANN, Carl",GER,Men,Open Event,Gold
150,1896,Athens,Wrestling,Wrestling Gre-R,"TSITAS, Georgios",GRE,Men,Open Event,Silver
1112,1904,St Louis,Wrestling,Wrestling Free.,"THIEFENTHALER, Gustav",USA,Men,- 47.6KG (Light-Flyweight),Bronze
1113,1904,St Louis,Wrestling,Wrestling Free.,"CURRY, Robert",USA,Men,- 47.6KG (Light-Flyweight),Gold
...,...,...,...,...,...,...,...,...,...
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [24]:
df.head()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
1,1896,Athens,Aquatics,Swimming,"HERSCHMANN, Otto",AUT,Men,100M Freestyle,Silver
2,1896,Athens,Aquatics,Swimming,"DRIVAS, Dimitrios",GRE,Men,100M Freestyle For Sailors,Bronze
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
4,1896,Athens,Aquatics,Swimming,"CHASAPIS, Spiridon",GRE,Men,100M Freestyle For Sailors,Silver

In [25]:
df.tail()

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
31160,2012,London,Wrestling,Wrestling Freestyle,"JANIKOWSKI, Damian",POL,Men,Wg 84 KG,Bronze
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold
31162,2012,London,Wrestling,Wrestling Freestyle,"TOTROV, Rustam",RUS,Men,Wg 96 KG,Silver
31163,2012,London,Wrestling,Wrestling Freestyle,"ALEKSANYAN, Artur",ARM,Men,Wg 96 KG,Bronze
31164,2012,London,Wrestling,Wrestling Freestyle,"LIDBERG, Jimmy",SWE,Men,Wg 96 KG,Bronze

In [27]:
df[df["Medal"]=="Gold"]

,Year,City,Sport,Discipline,Athlete,Country,Gender,Event,Medal
0,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,100M Freestyle,Gold
3,1896,Athens,Aquatics,Swimming,"MALOKINIS, Ioannis",GRE,Men,100M Freestyle For Sailors,Gold
6,1896,Athens,Aquatics,Swimming,"HAJOS, Alfred",HUN,Men,1200M Freestyle,Gold
9,1896,Athens,Aquatics,Swimming,"NEUMANN, Paul",AUT,Men,400M Freestyle,Gold
13,1896,Athens,Athletics,Athletics,"BURKE, Thomas",USA,Men,100M,Gold
...,...,...,...,...,...,...,...,...,...
31145,2012,London,Wrestling,Wrestling Freestyle,"NOROOZI, Omid Haji",IRI,Men,Wg 60 KG,Gold
31149,2012,London,Wrestling,Wrestling Freestyle,"KIM, Hyeonwoo",KOR,Men,Wg 66 KG,Gold
31153,2012,London,Wrestling,Wrestling Freestyle,"VLASOV, Roman",RUS,Men,Wg 74 KG,Gold
31157,2012,London,Wrestling,Wrestling Freestyle,"KHUGAEV, Alan",RUS,Men,Wg 84 KG,Gold
31161,2012,London,Wrestling,Wrestling Freestyle,"REZAEI, Ghasem Gholamreza",IRI,Men,Wg 96 KG,Gold

In [28]:
df.describe()

               Year
count  31165.000000
mean    1970.482785
std       33.158416
min     1896.000000
25%     1948.000000
50%     1980.000000
75%     2000.000000
max     2012.000000

In [29]:
print(df[10:20:2])

    Year    City      Sport Discipline             Athlete Country Gender  \
10  1896  Athens   Aquatics   Swimming   PEPANOS, Antonios     GRE    Men
12  1896  Athens  Athletics  Athletics    SZOKOLYI, Alajos     HUN    Men
14  1896  Athens  Athletics  Athletics      HOFMANN, Fritz     GER    Men
16  1896  Athens  Athletics  Athletics  GOULDING, Grantley     GBR    Men
18  1896  Athens  Athletics  Athletics        FLACK, Edwin     AUS    Men

             Event   Medal
10  400M Freestyle  Silver
12            100M  Bronze
14            100M  Silver
16    110M Hurdles  Silver
18           1500M    Gold